### ISSUE TITLE
Mediaplayer bei Suchergebnis spielt weiter nach betätigen des zurück buttons

### ISSUE THREAD

**Issue by SteveCharleston** [SteveCharleston/RiG#18]

**Comment by SteveCharleston** [comment]
Innerhalb der OnDestroy von Bandhören werden alle laufenden Player nun beendet

**Comment by spidanet** [comment]
Songs spielen beim Sucherergbnis nach dem Zurückgehen immer noch. Spiele ich dann einen weiteren Song, crasht die App
