### ISSUE TITLE
ROUND_COMPLETED wird nicht überprüft

### ISSUE THREAD

**Issue by spidanet** [SteveCharleston/RiG#21]
der Fehler-Code ROUND_COMPLETED wird nicht abgefragt. In dem Fall stürzt die App ab. (betrifft getBand.php)

**Comment by SteveCharleston** [comment]
Laden der Band wurde unbeabsichtigt gleichzeitig mit dem Aufrufen der Topliste fortgesetzt. Da keine Band zum laden da war crashte die App

**Comment by spidanet** [comment]
ROUND_COMPLETE wird immer noch nicht abgefragt. Startet die App bspw. mit user8 stürzt sie ab

**Comment by SteveCharleston** [comment]
Oh okay, ich schau mir dass so bald wie möglich an

**Comment by SteveCharleston** [comment]
Oh okay, ich schau mir dass so bald wie möglich an

**Comment by spidanet** [comment]
Also nach dem installieren der App über den Playstore, kann ich momentan das Problem auch nicht mehr nachvollziehen.
