### ISSUE TITLE
Musik läuft weiter beim Beenden der App mit "Zurück"-Taste

### ISSUE THREAD

**Issue by spidanet** [SteveCharleston/RiG#22]
Wird die App mit dem Home-Button (Mitte) geschlossen bzw. minimiert, kann ein bereits abspielender Songs auch wieder beendet werden.
Verlasse ich die App während des Abspielens aber mit der Zurücktaste (Song spielt weiter) und öffne sie erneut, dann kann ich den Song nicht mehr anhalten.

**Comment by SteveCharleston** [comment]
Drücken des zurück Buttons beendet die App nicht mehr sondern minimiert diese nur noch, wenn wir uns im obersten Bandhören-Bildschirm befinden.

**Comment by spidanet** [comment]
Wenn ich die App mit dem mittleren home Button minimiere, kann ich sie wieder aufrufen und ein laufendes Lied anhalten. 

Wenn ich die App aber mit dem linken zurück Button minimiere und dann wieder öffne, öffnet sich eine neue Instanz und ich kann ein bereits laufendes Lied nicht mehr beenden.

**Comment by SteveCharleston** [comment]
Oh Sorry, hatte mich bei dem letzten Kommentar ungenau ausgedrückt. Konnte das Verhalten auf jeden fall nachvollziehen. Was ich meinte, ist dass ich den Bug gefixt habe und in der Aktuellen version die App nur noch minimiert wird statt beendet zu werden, inklusive weiterhin bedienbarer Player-Buttons.
