### ISSUE TITLE
Absturz nach erneutem Abspielen eines Songs nach Seitenwechsel

### ISSUE THREAD

**Issue by spidanet** [SteveCharleston/RiG#25]
App-Absturz nach folgender Aktions-Reihenfolge:

Zufällige Band > Starte Song > Wechsele die Seite (Suche oder Über) > gehe zurück > (Song ist noch grün hinterlegt) Spiele Song erneut ab (oder auch anderen Song) > Absturz

**Comment by SteveCharleston** [comment]
Code angepasst, jetzt dürfte der Player nach wechsel in einen andern Bildschirm und Rückkehr korrekt funktionieren
